cc: play_again0 play_again1 play_again2 play_again3

play_again0: 
	gcc -o play_again0.out play_again0.c

play_again1: 
	gcc -o play_again1.out play_again1.c

play_again2: 
	gcc -o play_again2.out play_again2.c

play_again3: 
	gcc -o play_again3.out play_again3.c

.PHONY: clean

clean:
	rm -f *.o *.out
